format = """
$directory\ 
$git_branch\
$git_commit\
$git_state\
$git_status
$character
"""

right_format = """
$cmd_duration
"""

[character]
success_symbol = '[❯](purple)'
error_symbol = '[❯](red)'

[cmd_duration]
min_time = 5000
format = '[$duration](bold yellow)'

[directory]
read_only = ''
truncation_length = 0
truncate_to_repo = false

[git_branch]
format = '[$branch(:$remote_branch)]($style)'
style = 'bold black'

[git_status]
format = '([$all_status$ahead_behind]($style))'
style = 'bold black'
modified = '*'
untracked = '*'
staged = '*'
deleted = '*'
