format = """
$directory$username$hostname\ 
$git_branch\
$git_commit\
$git_state\
$git_status
$character
"""

right_format = """
$cmd_duration
"""

[username]
format = "[\\($user@]($style)"
style_user = 'bold black'
style_root = 'bold black'

[hostname]
format = "[$hostname\\)]($style) "
style = 'bold black'

[character]
success_symbol = '[❯](purple)'
error_symbol = '[❯](red)'

[cmd_duration]
min_time = 5000
format = '[$duration](bold yellow)'

[directory]
read_only = ''
truncation_length = 0
truncate_to_repo = false

[git_branch]
format = '[$branch(:$remote_branch)]($style)'
style = 'bold black'

[git_status]
format = '([*[$ahead_behind](bold cyan)]($style))'
style = 'bold black'
ahead = ' ⇡'
behind = ' ⇣'
conflicted = ''
untracked = ''
stashed = ''
modified = ''
staged = ''
renamed = ''
deleted = ''
typechanged = ''
